START OF FILE

Start by setting up the notebook and the dataframe

In [1]:
#import everything that is necessary for this notebook
import pandas as pd
import numpy as np

#create dataframe from the dataset
df = pd.read_csv("music_genre.csv")

In this dataset, the tempo feature uses ?'s for missing values, and the duration_ms uses negative values for missing values. I decided to replace all of these with their respective mean's.

In [2]:
#get the number of rows in the dataframe
size = len(df.index)
#initialize variables

for x in range(size):
    #checks for bad tempos
    if df.at[x, "tempo"] == "?":
        df.at[x, "tempo"] = np.NaN
    #checks if there is only a bad duration
    if df.at[x, 'duration_ms'] <= 0:
        df.at[x, 'duration_ms'] = np.NaN
#prints out the results for comparison
df["tempo"] = pd.to_numeric(df["tempo"])

df['tempo'] = df['tempo'].replace(np.NaN, df['tempo'].mean())
df['duration_ms'] = df['duration_ms'].replace(np.NaN, df['duration_ms'].mean())


I chose to delete the columns below because they were all information about the song rather than details of the song itself.

In [3]:
#deletes the columns
df = df.drop(columns=['instance_id', "artist_name", "track_name", "obtained_date",])

#show types of each feature
print(df.dtypes)

#displays what is left
df.describe().transpose()

popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo               float64
valence             float64
music_genre          object
dtype: object


count           mean            std           min  \
popularity        50000.0      44.220420      15.542008      0.000000   
acousticness      50000.0       0.306383       0.341340      0.000000   
danceability      50000.0       0.558241       0.178632      0.059600   
duration_ms       50005.0  245503.541466  105781.088663  15509.000000   
energy            50000.0       0.599755       0.264559      0.000792   
instrumentalness  50000.0       0.181601       0.325409      0.000000   
liveness          50000.0       0.193896       0.161637      0.009670   
loudness          50000.0      -9.133761       6.162990    -47.046000   
speechiness       50000.0       0.093586       0.101373      0.022300   
tempo             50005.0     119.952961      29.074243     34.347000   
valence           50000.0       0.456264       0.247119      0.000000   

                          25%            50%            75%          max  
popularity            34.0000      45.000000      56.000000       99.000  
acousticness           0.0200       0.144000       0.552000        0.996  
danceability           0.4420       0.568000       0.687000        0.986  
duration_ms       194875.0000  236040.000000  268600.000000  4830606.000  
energy                 0.4330       0.643000       0.815000        0.999  
instrumentalness       0.0000       0.000158       0.155000        0.996  
liveness               0.0969       0.126000       0.244000        1.000  
loudness             -10.8600      -7.276500      -5.173000        3.744  
speechiness            0.0361       0.048900       0.098525        0.942  
tempo                 96.7770     119.952961     139.465000      220.276  
valence                0.2570       0.448000       0.648000        0.992

The above table shows that loudness has both negative and positive values, since I eventually want all parameters to be between zero and one, I want to shift this. I also want to change the key, mode, and genre to numbers rather than objects so they will appear and can be normalized.

In [4]:

#store the inverse of the minimum value in the loudness column for later
minimum = df['loudness'].min() * -1

#loop through every single row to manipulate the data how I need it
for x in range(size):
    
    #Adds the inverse of the minumum loudness to every loudness, ensuring that all values are above or equal to zero
    df.at[x, 'loudness'] = df.at[x, 'loudness'] + minimum
    
    #------------------------------------
    #if the genre of the song is rock, it changes to 1, every other genre changes to 0, as rock is the target genre
    if df.at[x, "music_genre"] == "Rock":
        df.at[x, "music_genre"] = 1.0
    else: 
        df.at[x, "music_genre"] = 0.0
    
    #-------------------------------------
    #changes the key of the song to a number from 1-12 incrementally, A = 1, A# = 2, B = 3, and so on
    currentKey = df.at[x, "key"]
    if currentKey == "A":
        df.at[x, "key"] = 1.0

    elif currentKey == "A#":
        df.at[x, "key"] = 2.0

    elif currentKey == "B":
        df.at[x, "key"] = 3.0

    elif currentKey == "C":
        df.at[x, "key"] = 4.0

    elif currentKey == "C#":
        df.at[x, "key"] = 5.0

    elif currentKey == "D":
        df.at[x, "key"] = 6.0

    elif currentKey == "D#":
        df.at[x, "key"] = 7.0

    elif currentKey == "E":
        df.at[x, "key"] = 8.0

    elif currentKey == "F":
        df.at[x, "key"] = 9.0

    elif currentKey == "F#":
        df.at[x, "key"] = 10.0

    elif currentKey == "G":
        df.at[x, "key"] = 11.0

    else:
        df.at[x, "key"] = 12.0
    
    #------------------------------
    #if the mode of the song is major it becomes 1, if minor it becomes 0
    if df.at[x, "mode"] == "Major":
        df.at[x, "mode"] = 1.0

    else: 
        df.at[x, "mode"] = 0.0


print(df.dtypes)

popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo               float64
valence             float64
music_genre          object
dtype: object


The table above shows that even after changing all of the data into numbers, the type of some columns are still objects.

In [5]:
#changes the data types from object to floats
df["music_genre"] = pd.to_numeric(df["music_genre"])
df["key"] = pd.to_numeric(df["key"])
df["mode"] = pd.to_numeric(df["mode"])
#confirms the types have changed
print(df.dtypes)

popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                 float64
liveness            float64
loudness            float64
mode                float64
speechiness         float64
tempo               float64
valence             float64
music_genre         float64
dtype: object


The table above shows that now each feature is a float.

In [6]:
#show data after all changes
df.describe().transpose()

count           mean            std           min  \
popularity        50000.0      44.220420      15.542008      0.000000   
acousticness      50000.0       0.306383       0.341340      0.000000   
danceability      50000.0       0.558241       0.178632      0.059600   
duration_ms       50005.0  245503.541466  105781.088663  15509.000000   
energy            50000.0       0.599755       0.264559      0.000792   
instrumentalness  50000.0       0.181601       0.325409      0.000000   
key               50005.0       6.354985       3.457513      1.000000   
liveness          50000.0       0.193896       0.161637      0.009670   
loudness          50000.0      37.912239       6.162990      0.000000   
mode              50005.0       0.641916       0.479442      0.000000   
speechiness       50000.0       0.093586       0.101373      0.022300   
tempo             50005.0     119.952961      29.074243     34.347000   
valence           50000.0       0.456264       0.247119      0.000000   
music_genre       50005.0       0.099990       0.299990      0.000000   

                          25%            50%            75%          max  
popularity            34.0000      45.000000      56.000000       99.000  
acousticness           0.0200       0.144000       0.552000        0.996  
danceability           0.4420       0.568000       0.687000        0.986  
duration_ms       194875.0000  236040.000000  268600.000000  4830606.000  
energy                 0.4330       0.643000       0.815000        0.999  
instrumentalness       0.0000       0.000158       0.155000        0.996  
key                    4.0000       6.000000       9.000000       12.000  
liveness               0.0969       0.126000       0.244000        1.000  
loudness              36.1860      39.769500      41.873000       50.790  
mode                   0.0000       1.000000       1.000000        1.000  
speechiness            0.0361       0.048900       0.098525        0.942  
tempo                 96.7770     119.952961     139.465000      220.276  
valence                0.2570       0.448000       0.648000        0.992  
music_genre            0.0000       0.000000       0.000000        1.000

The table above shows that all the data looks to now be in a useable form, however it still needs to be normalized.

In [7]:
#make it easier to perform functions on either only the target column or only the columns of the predictors

target = ['music_genre']
predictors = list(set(list(df.columns))-set(target))

#saves the number of the predictors and the number of rows
outSize = len(predictors)
inSize = len(df.index)

#loops through each predictor
for x in range(outSize):
    currentPred = predictors[x]
    #gets maximum value for that column
    maximum = df[currentPred].max()
    for y in range(inSize):
        #divides each value by the maximum in it's column
        df.at[y, currentPred] = df.at[y, currentPred] / maximum

Now I wanted to remove all missing values from the DataFrame and double check by looking to see if the counts of each feature match.

In [8]:
#Removes missing values
df = df.dropna()
#Use count column to verify
df.describe().transpose()

count      mean       std       min       25%       50%  \
popularity        50000.0  0.446671  0.156990  0.000000  0.343434  0.454545   
acousticness      50000.0  0.307613  0.342711  0.000000  0.020080  0.144578   
danceability      50000.0  0.566167  0.181168  0.060446  0.448276  0.576065   
duration_ms       50000.0  0.050823  0.021899  0.003211  0.040342  0.048861   
energy            50000.0  0.600355  0.264824  0.000793  0.433433  0.643644   
instrumentalness  50000.0  0.182330  0.326716  0.000000  0.000000  0.000159   
key               50000.0  0.529535  0.288102  0.083333  0.333333  0.500000   
liveness          50000.0  0.193896  0.161637  0.009670  0.096900  0.126000   
loudness          50000.0  0.746451  0.121343  0.000000  0.712463  0.783018   
mode              50000.0  0.641980  0.479423  0.000000  0.000000  1.000000   
speechiness       50000.0  0.099349  0.107615  0.023673  0.038323  0.051911   
tempo             50000.0  0.544558  0.131997  0.155927  0.439339  0.544558   
valence           50000.0  0.459944  0.249112  0.000000  0.259073  0.451613   
music_genre       50000.0  0.100000  0.300003  0.000000  0.000000  0.000000   

                       75%  max  
popularity        0.565657  1.0  
acousticness      0.554217  1.0  
danceability      0.696755  1.0  
duration_ms       0.055606  1.0  
energy            0.815816  1.0  
instrumentalness  0.155622  1.0  
key               0.750000  1.0  
liveness          0.244000  1.0  
loudness          0.824434  1.0  
mode              1.000000  1.0  
speechiness       0.104591  1.0  
tempo             0.633152  1.0  
valence           0.653226  1.0  
music_genre       0.000000  1.0

In [9]:
print(df.duplicated().sum())

1370


In [10]:
df = df.drop_duplicates()
print(df.duplicated().sum())

0


After changing around the features, the variance can be used to make sure to use the most impactful features.

In [11]:
df.head()

popularity  acousticness  danceability  duration_ms    energy  \
0    0.272727      0.004699      0.661258     0.050823  0.941942   
1    0.313131      0.012751      0.630832     0.045190  0.890891   
2    0.282828      0.003072      0.628803     0.044635  0.755756   
3    0.343434      0.025502      0.784990     0.034545  0.700701   
4    0.323232      0.004669      0.647059     0.046033  0.587588   

   instrumentalness       key  liveness  loudness  mode  speechiness  \
0          0.795181  0.166667     0.115  0.823883   0.0     0.079406   
1          0.953815  0.500000     0.124  0.787616   0.0     0.031847   
2          0.011847  1.000000     0.534  0.835381   1.0     0.036624   
3          0.002540  0.416667     0.157  0.837724   1.0     0.253715   
4          0.912651  0.833333     0.157  0.802914   1.0     0.043843   

      tempo   valence  music_genre  
0  0.458012  0.765121          0.0  
1  0.522081  0.535282          0.0  
2  0.581062  0.335685          0.0  
3  0.581153  0.272177          0.0  
4  0.658429  0.325605          0.0

In [12]:
from sklearn.feature_selection import VarianceThreshold
#create the threshold
vt = VarianceThreshold(threshold=.01)
#remove features with a low variance
vt.fit(df)
#grab the column names
mask = vt.get_support()
#add the column names back to the updated dataframe
df = df.loc[:, mask]
#update list of predictors
predictors = list(set(list(df.columns))-set(target))
df.head()

popularity  acousticness  danceability    energy  instrumentalness  \
0    0.272727      0.004699      0.661258  0.941942          0.795181   
1    0.313131      0.012751      0.630832  0.890891          0.953815   
2    0.282828      0.003072      0.628803  0.755756          0.011847   
3    0.343434      0.025502      0.784990  0.700701          0.002540   
4    0.323232      0.004669      0.647059  0.587588          0.912651   

        key  liveness  loudness  mode  speechiness     tempo   valence  \
0  0.166667     0.115  0.823883   0.0     0.079406  0.458012  0.765121   
1  0.500000     0.124  0.787616   0.0     0.031847  0.522081  0.535282   
2  1.000000     0.534  0.835381   1.0     0.036624  0.581062  0.335685   
3  0.416667     0.157  0.837724   1.0     0.253715  0.581153  0.272177   
4  0.833333     0.157  0.802914   1.0     0.043843  0.658429  0.325605   

   music_genre  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

Now that the data set has been normalized, had missing values removed, had duplicates removed, and added a variance threshold, it is time to split the data into testing and training.

In [13]:
#changes the dataframe into two numpy arrays
x = df[predictors].values
y = df[target].values
#Change y from a column-vector to a 1d array
y = np.ravel(y)

#split x and y arrays into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state=40)

Now the data is properly prepared and it is time to test out several models to compare the results. First model is a multi-layer perceptron, I chose this because mlp's are great for supervised learning problems and this one is specialized for classification. For evaluation metrics I chose the confusion matrix so I can see the actual number of correctly categorized entries, and I chose the classification report so I can see the precision and recall score.

In [14]:
#creates the model
from sklearn.neural_network import MLPClassifier
nodes = len(df.columns)
mlp = MLPClassifier(hidden_layer_sizes=(nodes,nodes,nodes), activation='relu', solver='adam', max_iter=500)
#fits model to the training data
mlp.fit(x_train, y_train)
#makes predictions on new testing data
predict_test = mlp.predict(x_test)

#shows results of predictions of training data
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test, predict_test))

[[12475   610]
 [  715   789]]
              precision    recall  f1-score   support

         0.0       0.95      0.95      0.95     13085
         1.0       0.56      0.52      0.54      1504

    accuracy                           0.91     14589
   macro avg       0.75      0.74      0.75     14589
weighted avg       0.91      0.91      0.91     14589



This model has the highest accuracy out of all the models, the most amount of true negatives, and the least amount of false negatives.

Then I tried logistic regression because the dependent variable is binary, it is either rock music or not rock music with nothing in between.

In [15]:
#creates the model
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)
#fits model to the training data
lr.fit(x_train, y_train)
#makes predictions on new testing data
predict_test = lr.predict(x_test)

#shows results of predictions of training data
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test, predict_test))

[[12773   312]
 [ 1078   426]]
              precision    recall  f1-score   support

         0.0       0.92      0.98      0.95     13085
         1.0       0.58      0.28      0.38      1504

    accuracy                           0.90     14589
   macro avg       0.75      0.63      0.66     14589
weighted avg       0.89      0.90      0.89     14589



This model has the most amount of true positives and the least amount of false positives.

KNN I chose this because it is a popular and simple model for classification.

In [16]:
#creates the model
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
#fits model to the training data
neigh.fit(x_train, y_train)
#makes predictions on new testing data
predict_test = neigh.predict(x_test)

#shows results of predictions of training data
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test, predict_test))

[[12655   430]
 [ 1134   370]]
              precision    recall  f1-score   support

         0.0       0.92      0.97      0.94     13085
         1.0       0.46      0.25      0.32      1504

    accuracy                           0.89     14589
   macro avg       0.69      0.61      0.63     14589
weighted avg       0.87      0.89      0.88     14589



This model has the least amount of true negatives, the most amount of false negatives, and the lowest accuracy score.

Random Forest Classifier I chose this because it is popular for classification and good with large datasets

In [17]:
#creates the model
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
#fits model to the training data
rfc.fit(x_train, y_train)
#makes predictions on new testing data
predict_test = rfc.predict(x_test)

#shows results of predictions of training data
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test, predict_test))

[[12610   475]
 [  982   522]]
              precision    recall  f1-score   support

         0.0       0.93      0.96      0.95     13085
         1.0       0.52      0.35      0.42      1504

    accuracy                           0.90     14589
   macro avg       0.73      0.66      0.68     14589
weighted avg       0.89      0.90      0.89     14589



This model had very middle of the road results.

After looking at the results, I believe the best model to use would be the multi-layer perceptron classifier. The reasoning behind this is it had the best accuracy score out of all four, a competitive true postive score, the highest true negative score. Overall it has very competitve precision and recall scores.